#!/bin/bash

taskId="$2"
if [[ "$taskId" == '' ]]; then
    printf "task id: "
    read -r taskId
fi
printf "nome: "
read -r name
newName="${name// /-}"
if [[ "$taskId" != "" ]]; then
    branchName="#$taskId-$newName"
else
    branchName="$newName"
fi
git flow "$1" start "$branchName"
